name: deepseek_service
description: A dart package for GPT Ai medical API integration.
version: 1.0.1+9

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.8.0+1
  json_annotation: any
  freezed: any
  freezed_annotation: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  
